import Head from 'next/head'
import {useState} from "react";
export default function Home() {
    const [amount, setAmount] = useState(5)
    const [email, setEmail] = useState("")


    const getPaymentLink = async (email, amount) => {
        const data = await fetch(`/api/invoice/create?email=${email}&amount=${amount}`)
        return (await data.json()).link
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        const link = await getPaymentLink(email, amount)
        window.location.href = link;
    }

    return (
        <div>
            <Head>
                <title>CryptoCloud integration</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <form onSubmit={handleSubmit}>
                    <label htmlFor="amount">Amount (USD)</label><br/>
                    <input type="number" min={2} max={20} id="amount" value={amount} onChange={(e) => setAmount(+e.target.value)}/><br/>
                    <label htmlFor="email">email</label><br/>
                    <input type="text" id="email" value={email} onChange={(e) => setEmail(e.target.value)}/><br/><br/>
                    <input type="submit" value="Submit"/>
                </form>
            </main>
        </div>
)
}
